# Generated by Django 6.0.1 on 2026-01-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_booking_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats_reserved',
            field=models.JSONField(default=list),
        ),
    ]
