# Generated by Django 6.0.1 on 2026-01-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_booking_seats_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
